[project]
name = "AutoSurfaceVehicle"
version = "0.1.0"
requires-python = ">3.9"
dependencies = [
    "pymunk",
    "pygame",
    "numpy",
    "pandas",
    "pyyaml",
    "xarray",
    "netCDF4"
]

[build-system]
requires = ["setuptools"]

[tool.setuptools.packages.find]
exclude = ["data*", "config*"]
