# Global parameters for all sims
# All units are in pixels and discrete time iterations unless otherwise stated

world:
  sim_time: 25 # seconds
  FPS: 30
  screen_size: 500
  grid_num: 50

robot:
  robot_vel: 4.
  noise_factor: 0.0138
